# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_study_identifier', models.CharField(max_length=50)),
                ('import_date', models.DateTimeField()),
                ('import_status', models.BooleanField()),
                ('import_details', models.TextField()),
                ('db_server_url', models.CharField(max_length=50)),
                ('db_name', models.CharField(max_length=50)),
                ('cbio_base_url', models.CharField(max_length=100)),
            ],
        ),
    ]
